# Generated by Django 3.0.3 on 2020-02-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotniska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Lotniska',
            },
        ),
        migrations.CreateModel(
            name='Loty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_odlotu', models.DateTimeField()),
                ('data_przylotu', models.DateTimeField()),
                ('numer_lotu', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Loty',
            },
        ),
        migrations.CreateModel(
            name='Pasazerowie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Pasazerowie',
            },
        ),
        migrations.CreateModel(
            name='Samoloty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_miejsc', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Samoloty',
            },
        ),
        migrations.CreateModel(
            name='Wymagania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Wymagania',
            },
        ),
        migrations.CreateModel(
            name='Trasy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejsce_odlotu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miejsce_odlotu', to='reservationsapp.Lotniska')),
                ('miejsce_przylotu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miejsce_przylotu', to='reservationsapp.Lotniska')),
            ],
            options={
                'verbose_name_plural': 'Trasy',
            },
        ),
        migrations.CreateModel(
            name='Siedzenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miejsce', models.IntegerField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationsapp.Loty')),
                ('pasazer', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='reservationsapp.Pasazerowie')),
                ('samolot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationsapp.Samoloty')),
            ],
            options={
                'verbose_name_plural': 'Siedzenia',
            },
        ),
        migrations.CreateModel(
            name='Rezerwacje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('pasazer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationsapp.Pasazerowie')),
            ],
            options={
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
        migrations.CreateModel(
            name='MiejscaSpecjalne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siedzenie', models.ManyToManyField(to='reservationsapp.Siedzenia')),
                ('wymaganie', models.ManyToManyField(to='reservationsapp.Wymagania')),
            ],
            options={
                'verbose_name_plural': 'Miejsca Specjalne',
            },
        ),
        migrations.AddField(
            model_name='loty',
            name='samolot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationsapp.Samoloty'),
        ),
        migrations.AddField(
            model_name='loty',
            name='trasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservationsapp.Trasy'),
        ),
    ]
