# Generated by Django 3.0.3 on 2020-02-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiejscaSpecjalne',
        ),
        migrations.DeleteModel(
            name='Wymagania',
        ),
    ]
