# Generated by Django 3.0.3 on 2020-02-12 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservationsapp', '0002_auto_20200211_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezerwacje',
            name='lot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reservationsapp.Loty'),
        ),
    ]
